version: '3.8'

services:
  todo-app:
    image: khunball/docker-todo-app
    depends_on: 
      - mssql
    build:
      context: .
    container_name: go-api
    hostname: go-api
    networks:
      - mynet
    ports:
      - 4200:80
      - 80:1234
    environment:
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
      - DATABASE=${DATABASE}
    deploy:
      restart_policy:
        condition: on-failure
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: mssql
    hostname: db
    networks:
      - mynet
    ports:
      - 1433:1433
    volumes:
      - mssql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${PASSWORD}
    # command: start-single-node --insecure

volumes:
  mssql:
    # external: true

networks:
  mynet:
    driver: bridge
